# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


driver = webdriver.Firefox()
vars = {}



driver.get("http://10.10.252.161/clearanceslipApp")
driver.set_window_size(1457, 881)
driver.find_element(By.NAME, "login").send_keys("superadmin")
driver.find_element(By.NAME, "password").send_keys("FVbTBp7B7get7dMdC7QAByEyaw6S9jLh")
driver.find_element(By.CSS_SELECTOR, ".MuiButton-contained > .MuiButton-label").click()
driver.find_element(By.CSS_SELECTOR, ".MuiList-root:nth-child(10) .MuiTypography-root").click()
driver.execute_script("window.scrollTo(0,0)")

driver.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div/div[1]/button[2]").click()
driver.find_element(By.NAME, "stuffName").click()
driver.find_element(By.NAME, "stuffName").send_keys("Komputer")
driver.find_element(By.ID, "demo-simple-select").click()
atr = driver.find_element(By.XPATH, "/html/body/div[3]/div[3]")
print(atr)
driver.find_element(By.XPATH, "/html/body/div[3]/div[3]/ul/li[4]").click()
driver.find_element(By.XPATH, "/html/body/div[1]/div/main/div/div[1]/form/div/div[5]/label").click()
driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root-1191:nth-child(4)").click()
driver.find_element(By.CSS_SELECTOR, ".MuiButton-label-1163").click()
element = driver.find_element(By.CSS_SELECTOR, ".MuiTableRow-root:nth-child(11) .MuiSvgIcon-root")
actions = ActionChains(driver)
actions.move_to_element(element).perform()
element = driver.find_element(By.CSS_SELECTOR, "body")
actions = ActionChains(driver)
actions.move_to_element(element, 0, 0).perform()
driver.find_element(By.CSS_SELECTOR, ".MuiTableRow-root:nth-child(11) path").click()
driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(2) > .MuiButton-label").click()

driver.quit()
